rust/osm2lanes-web/src/main.rs
rust/osm2lanes/Cargo.toml
rust/osm2lanes/src/lib.rs
rust/osm2lanes/src/main.rs
rust/osm2lanes/src/transform.rs

Regroup Tags to be part of the public interface, as it appears to be widely used.

Rust: Refactor Tags Struct

---

data/spec-lanes.json

Both: for shared turning lanes, suicide lanes, bidirectional bicycle lanes, and sidewalks
None: for buffer areas, closed lanes, etc.

Add More Lane Directions

---

rust/osm2lanes-web/src/main.rs
rust/osm2lanes/src/lib.rs
rust/osm2lanes/src/transform.rs

OSM to lane transformation cannot always be perfect
There will often be cases where we can or need to make assumptions, these should be reported as warnings.
There will sometimes be conflicting tags, these should be reported as errors.
The interface gets updated with these types.

Rust: Add Warnings

---

rust/osm2lanes/src/lib.rs
rust/osm2lanes/src/transform.rs

Prepare the boilerplate for lanes2osm.
We roundtrip lanes->osm->lanes, and not the other way around, because we expect osm to lanes to be a many to one mapping.

Rust: Prepare for Rountrip Testing

---

data/tests.json
rust/osm2lanes/src/lib.rs
rust/osm2lanes/src/transform.rs

Attempt to cleanup bicycle lane processing.
Ended up making thinigs worse...
While doing this I determined I want better tag combination semantics. Passing around Option<Enum> values is not fun.
I also needed to disable some tests pending bidirectional cyclepath support.
Please advise on how incremental you want me to do this...
All skipped tests are due to bidirectional or LHD cyclepaths.

Rust: Refactor Bicycle - First Pass

---

rust/osm2lanes/src/transform.rs

Require the output of lanes_to_tags to rountrip, or throw an error.

Rust: Lanes To Tags Requires Rountrip

---

rust/osm2lanes/src/transform/error.rs
rust/osm2lanes/src/transform/mod.rs
rust/osm2lanes/src/transform/tags_to_lanes/non_motorized.rs

The important functional changes:
- How we serialize errors (as display)

Rust: Refactor Tranform Error

---

.githooks/check
data/tests.yml
rust/osm2lanes/src/lib.rs
rust/osm2lanes/src/tags.rs
rust/osm2lanes/src/test.rs
rust/osm2lanes/src/transform/tags_to_lanes/mod.rs

Re-enable testing, accidentally broken during a refactor
Allow ignoring warnings.
Loosen the warnings generated by lanes:* -> This should fix the website...

Rust: Fix Broken Testing

---

rust/osm2lanes-web/Cargo.toml
rust/osm2lanes-web/assets/css/main.css
rust/osm2lanes-web/src/main.rs
rust/osm2lanes/Cargo.toml
rust/osm2lanes/src/lib.rs
rust/osm2lanes/src/locale.rs

Uses celec dependency for ISO 3166 country definitions.
The default selected country should maybe be set initially, but for now is not.

Rust Website: Add Country Support

---

rust/osm2lanes-web/src/draw.rs
rust/osm2lanes/src/locale.rs
rust/osm2lanes/src/road/lane.rs
rust/osm2lanes/src/test.rs
rust/osm2lanes/src/transform/lanes_to_tags.rs
rust/osm2lanes/src/transform/mod.rs
rust/osm2lanes/src/transform/tags_to_lanes/bicycle.rs
rust/osm2lanes/src/transform/tags_to_lanes/bus.rs
rust/osm2lanes/src/transform/tags_to_lanes/foot_shoulder.rs
rust/osm2lanes/src/transform/tags_to_lanes/mod.rs
rust/osm2lanes/src/transform/tags_to_lanes/non_motorized.rs
rust/osm2lanes/src/transform/tags_to_lanes/parking.rs
rust/osm2lanes/src/transform/tags_to_lanes/separator.rs

Add lane width to rust lane structs.
Locale now does the heavy lifting with travel_width.

Rust: Lane Width

---

web/index.html
web/serve_locally.py

The https://a-b-street.github.io/osm2lanes/ web interface is great, but an easier user flow is to just click a map and automatically grab the way from Overpass. This PR does the first half of that -- click a road in Mapbox, find the nearest way, display the road on the map (just as a line-string).
The second half will actually plug into osm2lanes; I'll resume #60 for that.
I'm doing this all in vanilla JS, no frameworks or anything. The goal is to make example code for other people to build off of, hopefully in time for FOSSGIS this weekend.

Start a demo of clicking a road and plugging it into osm2lanes

---

CONTRIBUTING.md
rust/osm2lanes/Cargo.toml
rust/osm2lanes/src/lib.rs
rust/osm2lanes/src/wasm.rs
web/index.html

I believe this is the minimal work needed to call the Rust library from JS. It appears to work:
Still TODO: passing more options in, error handling, and an NPM package

Create WASM bindings and wire up into the vanilla JS Mapbox demo

---

.github/workflows/test.yml

Switch back to upstream and fix runs outside of a PR.

Rust: Fix Benchmarking

---

rust/osm2lanes/Cargo.toml
rust/osm2lanes/src/transform/error.rs
rust/osm2lanes/src/transform/lanes_to_tags/mod.rs
rust/osm2lanes/src/transform/mod.rs
rust/osm2lanes/src/transform/tags_to_lanes/error.rs
rust/osm2lanes/src/transform/tags_to_lanes/mod.rs
rust/osm2lanes/src/transform/tags_to_lanes/modes/bicycle.rs
rust/osm2lanes/src/transform/tags_to_lanes/modes/bus.rs
rust/osm2lanes/src/transform/tags_to_lanes/modes/foot_shoulder.rs
rust/osm2lanes/src/transform/tags_to_lanes/modes/non_motorized.rs
rust/osm2lanes/src/transform/tags_to_lanes/separator/mod.rs

Use std::panic::Location to idenitfy error locations
Refactoring with thiserror, another crate, or without may cut down on boilerplate

Rust: Add Error Locations

---

rust/osm2lanes/src/transform/tags_to_lanes/mod.rs
rust/osm2lanes/src/transform/tags_to_lanes/modes/bus.rs

In an attempt to make @BudgieInWA 's PR smaller.

Rust: Busway Scheme Refactor

---

data/tests.yml

Taking the tests.yml changes out of https://github.com/a-b-street/osm2lanes/pull/111

Add Lane Count Tests

---

data/tests.yml
rust/osm2lanes/src/locale.rs
rust/osm2lanes/src/tag/mod.rs
rust/osm2lanes/src/test.rs
rust/osm2lanes/src/transform/lanes_to_tags/mod.rs
rust/osm2lanes/src/transform/mod.rs
rust/osm2lanes/src/transform/tags_to_lanes/lane.rs
rust/osm2lanes/src/transform/tags_to_lanes/mod.rs
rust/osm2lanes/src/transform/tags_to_lanes/modes/bus.rs
rust/osm2lanes/src/transform/tags_to_lanes/modes/mod.rs

This is what https://github.com/a-b-street/osm2lanes/pull/111 would look like applied to:
- https://github.com/a-b-street/osm2lanes/pull/141
- https://github.com/a-b-street/osm2lanes/pull/145
This is getting to a reviewable size.

Split of "#111 Fix lane count calculation"

---

rust/osm2lanes/src/transform/tags_to_lanes/mod.rs
rust/osm2lanes/src/transform/tags_to_lanes/modes/bicycle.rs
rust/osm2lanes/src/transform/tags_to_lanes/modes/foot_shoulder.rs
rust/osm2lanes/src/transform/tags_to_lanes/road.rs

These are two quite big structs, so we begin a refactor by moving them out of mod to allow for better increments

Rust: Refactor RoadBuilder and LaneBuilder

---

osm2lanes/src/transform/tags_to_lanes/modes/bicycle.rs
osm2lanes/src/transform/tags_to_lanes/road.rs

Refactor bicycle.rs by injecting an intermediate Scheme.
This follows the scheme separation laid out by @BudgieInWA... somehwere? not sure which issue.

Refactor Bicycle Scheme

---

osm2lanes/src/tag/mod.rs
osm2lanes/src/tag/osm.rs
osm2lanes/src/transform/tags_to_lanes/error.rs
osm2lanes/src/transform/tags_to_lanes/mod.rs
osm2lanes/src/transform/tags_to_lanes/road.rs
osm2lanes/src/transform/tags_to_lanes/unsupported.rs

Move oneway parsing to a singular place,
and fix an error in access tag unimplemented logging

Refactor Oneway

---

data/tests.yml
osm2lanes-web/Cargo.toml
osm2lanes-web/assets/css/main.css
osm2lanes-web/src/control.rs
osm2lanes-web/src/main.rs
osm2lanes/src/test.rs

Add a convenient dropdown to website for good examples

Add Examples To Website

---

data/spec-lanes.json
data/tests.yml
osm-tags/src/access.rs
osm2lanes/src/road/lane.rs
osm2lanes/src/test.rs
osm2lanes/src/transform/lanes_to_tags/mod.rs
osm2lanes/src/transform/tags_to_lanes/modes/bicycle.rs
osm2lanes/src/transform/tags_to_lanes/modes/non_motorized.rs
osm2lanes/src/transform/tags_to_lanes/road.rs

Add Support For cycleway=opposite

---

osm-tags/src/lib.rs

It appears to be due to a duplication in tags in overpass' JSON response.
e.g. given way 3600044874
ISO3166-2=IT-21 is repeated 4 times.
The cause is unclear.

Deserializing Tags Crashing on Website

---

osm2lanes/src/test.rs

The `cfg_attr` stuff is less readable. Every caller of the tests (benchmark, running tests, the web app) needs to deserialize the YAML; `tests.rs` is meaningless without serde

Require serde in tests.rs

---

README.md
data/tests.yml
osm2lanes/src/transform/tags_to_lanes/modes/foot_shoulder.rs

This PR handles `sidewalk=separate` by silently ignoring it and not adding a sidewalk, because it's not the job of osm2lanes to figure out parallel ways. And it handles `sidewalk=none` by treating it the same as `no` and adding a deprecated warning.

Handle sidewalk=separate and none. Closes #249

---

data/tests.yml
osm2lanes/src/test.rs

The expected test output used to just be a list of lanes. When we added the outer `Road` structure, some of the tests changed, but not all. This PR fully migrates to the new expected output style and cleans up the transition stuff.
Overall goal: simplify how the tests work, make it easy to crank out new ones.

Fully switch over to new test output

---

osm2lanes-web/Cargo.toml
osm2lanes-web/src/lib.rs
osm2lanes/Cargo.toml
osm2lanes/src/road/mod.rs
osm2lanes/src/test.rs

If you want to add a test case to the .yaml today, you have to:
- copy paste an existing example, then change some things about it
- decide where in the .yaml file it should go (based on comments about organization)
This PR mostly fixes the first. You can use the web app, get the current output, and generate the YAML. You have to manually fix it up -- usually because the expected output is wrong -- but this is much faster workflow.

Add a button to generate example test YAML from the web app
