a-b-street/osm2lanes

.gitignore, README.md, rust/osm2lanes/Cargo.toml, rust/osm2lanes/src/lib.rs, rust/osm2lanes/src/main.rs, rust/osm2lanes/src/transform.rs
This is A/B Street's implementation standalone and cleaned up slightly. After we create and iterate on the schema in this repo, I'll eventually make A/B Street depend on this repo instead.
=> Copy over the Rust implementation

data/tests.json, kotlin/src/test/kotlin/Test.kt, python/tests/test_lanes.py, rust/osm2lanes/src/lib.rs
To make specification file a bit more clear.
=> Change string way URL to integer way identifier

.gitignore, rust/.gitignore, rust/Cargo.toml, rust/README.md, rust/Release.toml, rust/Trunk.toml, rust/osm2lanes-web/Cargo.toml, rust/osm2lanes-web/assets/css/main.css, rust/osm2lanes-web/index.html, rust/osm2lanes-web/src/main.rs, rust/release.sh, rust/rust-toolchain.toml
Implemented in Rust using Yew
Resolves https://github.com/a-b-street/osm2lanes/issues/4
Demo: https://droogmic.github.io/osm2lanes/
=> Add Web Viewer

rust/osm2lanes-web/src/main.rs, rust/osm2lanes/src/lib.rs
Move ascii and utf display printing to library.
=> Refactor Lane Print

rust/osm2lanes-web/Cargo.toml, rust/osm2lanes-web/assets/css/main.css, rust/osm2lanes-web/src/draw.rs, rust/osm2lanes-web/src/main.rs, rust/release.sh
I can draw some pretty lanes this way... but I just chose the first library I could find.
=> Demo Web Canvas with Piet

rust/osm2lanes-web/src/main.rs, rust/osm2lanes/src/lib.rs, rust/osm2lanes/src/main.rs, rust/osm2lanes/src/transform.rs
Refactoring with no (intentional) change of functionality.
=> Rust: Refactor Tranform get_lane_specs_ltr

data/githooks/pre-push, data/tests.json, kotlin/src/main/kotlin/Main.kt, pyproject.toml, python/osm2lanes/core.py, rust/osm2lanes-web/src/draw.rs, rust/osm2lanes/src/lib.rs, rust/osm2lanes/src/transform.rs
Also: add information to test data including mapillary and comments for improvement
=> Add Support For Lane Direction Both

data/tests.json, python/osm2lanes/core.py
Just synced Kotlin and Python functionality.
=> Support bus lanes in Python

rust/osm2lanes/src/lib.rs, rust/osm2lanes/src/tags.rs, rust/osm2lanes/src/transform.rs
There are some generic type stuff in rust that I am not too happy with...
=> Rust: Refactor Tags

rust/osm2lanes-web/assets/css/main.css, rust/osm2lanes-web/src/main.rs, rust/osm2lanes/Cargo.toml, rust/osm2lanes/src/lib.rs, rust/osm2lanes/src/tags.rs, rust/osm2lanes/src/transform.rs
As we said we wanted.
I haven't deployed an example yet, need to steel your action....
=> Rust: Web Site Roundtrip Support

data/tests.json, rust/osm2lanes/src/lib.rs, rust/osm2lanes/src/tags.rs, rust/osm2lanes/src/transform.rs
Next up: upgrade the web version with this.
=> Rust: Finish Lane to OSM Tags

data/tests.yml, rust/osm2lanes-web/src/main.rs, rust/osm2lanes/src/lib.rs, rust/osm2lanes/src/locale.rs, rust/osm2lanes/src/main.rs, rust/osm2lanes/src/transform/lanes_to_tags.rs, rust/osm2lanes/src/transform/mod.rs, rust/osm2lanes/src/transform/tags_to_lanes.rs
I promise I'll start adding features soon, but refactoring is just so therapeutic...
=> Rust: Refactor Transform By Direction

data/tests.yml, kotlin/build.gradle.kts, kotlin/src/main/kotlin/Main.kt, kotlin/src/test/kotlin/Test.kt, python/osm2lanes/core.py, python/tests/test_lanes.py, rust/osm2lanes/src/lib.rs, rust/osm2lanes/src/locale.rs, rust/osm2lanes/src/transform/lanes_to_tags.rs, rust/osm2lanes/src/transform/mod.rs, rust/osm2lanes/src/transform/tags_to_lanes.rs
Mainly reworking Bicycle, Sidewalk and Shoulder
=> Rust TDD Features

README.md
Minor changes and additions to the readme.
=> Readme format add docs webview

data/tests.yml, rust/osm2lanes-web/src/draw.rs, rust/osm2lanes-web/src/main.rs, rust/osm2lanes/src/lib.rs, rust/osm2lanes/src/locale.rs, rust/osm2lanes/src/transform/lanes_to_tags.rs, rust/osm2lanes/src/transform/mod.rs, rust/osm2lanes/src/transform/tags_to_lanes/mod.rs, rust/osm2lanes/src/transform/tags_to_lanes/separator.rs
Work towards data driven rendering.
=> Rust: Add Separator Rendering

data/tests.yml, rust/osm2lanes/src/tags.rs, rust/osm2lanes/src/transform/tags_to_lanes/foot_shoulder.rs
Add sidewalk support, fixes issue #49.
=> Rust: Sidewalk

LICENSE, README.md, rust/osm2lanes-web/Cargo.toml, rust/osm2lanes/Cargo.toml
=> Add Apache license

.githooks/check, .github/workflows/test.yml, rust/osm2lanes/src/transform/tags_to_lanes/bus.rs, rust/osm2lanes/src/transform/tags_to_lanes/mod.rs, rust/rust-toolchain.toml
A different computer, and a different output from clippy... I guess I need to try and figure out how to have a fixed version of clippy...
=> Rust: Clippy Fixes

rust/osm2lanes-web/src/main.rs, rust/osm2lanes/src/transform/tags_to_lanes/bus.rs, rust/osm2lanes/src/transform/tags_to_lanes/mod.rs
Note however, that the lane calculations still has a bug,
where lanes=6 ends up as 5 lanes...
=> Rust: Fix Website

.githooks/check, .githooks/test_kotlin, .githooks/test_python, .githooks/test_rust, .githooks/test_schema, .github/workflows/test.yml, CONTRIBUTING.md, README.md
Split stuff up
Add caching to python
Make scripts the same between hooks and actions.
I still dislike actions.
=> Rework Git Hooks and Actions

rust/osm2lanes/src/tag/mod.rs
Test public interfaces for tags to prepare for refactoring.
=> Rust: Add Tests for Tags

rust/osm2lanes/src/transform/mod.rs, rust/osm2lanes/src/transform/tags_to_lanes/bicycle.rs, rust/osm2lanes/src/transform/tags_to_lanes/bus.rs, rust/osm2lanes/src/transform/tags_to_lanes/foot_shoulder.rs, rust/osm2lanes/src/transform/tags_to_lanes/mod.rs, rust/osm2lanes/src/transform/tags_to_lanes/parking.rs
An internal builder style construct as proposed in: https://github.com/a-b-street/osm2lanes/issues/79
=> Rust: refactor transform lanes

rust/osm2lanes/src/test.rs, rust/osm2lanes/src/transform/error.rs, rust/osm2lanes/src/transform/mod.rs, rust/osm2lanes/src/transform/tags_to_lanes/bicycle.rs, rust/osm2lanes/src/transform/tags_to_lanes/bus.rs, rust/osm2lanes/src/transform/tags_to_lanes/foot_shoulder.rs, rust/osm2lanes/src/transform/tags_to_lanes/mod.rs, rust/osm2lanes/src/transform/tags_to_lanes/parking.rs
A continuation of the previous work.
=> Rust refactor lanebuilder

data/tests.yml, rust/osm2lanes/src/transform/error.rs, rust/osm2lanes/src/transform/lanes_to_tags.rs, rust/osm2lanes/src/transform/tags_to_lanes/bus.rs
Expand `busway:*=opposite_lane` and rework `bus:lanes=*`
=> Add Support for More Bus Lanes

data/tests.yml, rust/osm2lanes/src/tag/mod.rs, rust/osm2lanes/src/tag/osm.rs, rust/osm2lanes/src/transform/lanes_to_tags.rs, rust/osm2lanes/src/transform/mod.rs, rust/osm2lanes/src/transform/tags_to_lanes/mod.rs, rust/osm2lanes/src/transform/tags_to_lanes/non_motorized.rs
A follow-up will be needed to structurally solve roundtrip information retention
=> Add Highway Support

rust/osm2lanes/src/road/lane.rs, rust/osm2lanes/src/tag/mod.rs, rust/osm2lanes/src/tag/osm.rs, rust/osm2lanes/src/transform/tags_to_lanes/bicycle.rs, rust/osm2lanes/src/transform/tags_to_lanes/bus.rs, rust/osm2lanes/src/transform/tags_to_lanes/foot_shoulder.rs, rust/osm2lanes/src/transform/tags_to_lanes/mod.rs, rust/osm2lanes/src/transform/tags_to_lanes/non_motorized.rs, rust/osm2lanes/src/transform/tags_to_lanes/parking.rs
=> Add Road Builder and Update Highway

rust/osm2lanes-web/src/main.rs, rust/osm2lanes/src/road/mod.rs, rust/osm2lanes/src/tag/osm.rs, rust/osm2lanes/src/test.rs, rust/osm2lanes/src/transform/error.rs, rust/osm2lanes/src/transform/lanes_to_tags.rs, rust/osm2lanes/src/transform/mod.rs, rust/osm2lanes/src/transform/tags_to_lanes/mod.rs, rust/osm2lanes/src/transform/tags_to_lanes/non_motorized.rs, rust/osm2lanes/src/transform/tags_to_lanes/separator.rs
This changes the external interface in order to make it a bit more rich
=> Rust: Refactor Tags to Lanes to include Highway

data/tests.yml, rust/osm2lanes/src/tag/mod.rs, rust/osm2lanes/src/tag/osm.rs, rust/osm2lanes/src/transform/tags_to_lanes/mod.rs
Deadlines sneak up on us don't they...
=> Add basic support for Construction

rust/osm2lanes-web/src/draw.rs
Not sure why I didn't just finish this, the downsides of incremental development.
=> Add Parking Support

CONTRIBUTING.md, README.md, rust/rust-toolchain.toml
Help guide newcomers more clearly.
=> README and Rust Toolchain Updates

data/spec-lanes.json, data/tests.yml, rust/osm2lanes-web/src/draw.rs, rust/osm2lanes-web/src/main.rs, rust/osm2lanes/Cargo.toml, rust/osm2lanes/benches/benchmark_all_same.rs, rust/osm2lanes/src/locale.rs, rust/osm2lanes/src/road/marking.rs, rust/osm2lanes/src/test.rs, rust/osm2lanes/src/transform/lanes_to_tags.rs, rust/osm2lanes/src/transform/tags_to_lanes/mod.rs, rust/osm2lanes/src/transform/tags_to_lanes/separator.rs
The locale related parts of the code currently are getting a bit hairy.
I don't have a good design in mind, so I am waiting to implement some more so I can spot patterns before doing anything.
=> Rust: Add NL Autoweg 100km/h

rust/osm2lanes-bin/src/main.rs, rust/osm2lanes-web/assets/css/main.css, rust/osm2lanes-web/src/main.rs, rust/osm2lanes/src/locale.rs, rust/osm2lanes/src/overpass.rs, rust/osm2lanes/src/test.rs
=> Rust: Retrieve Locale from Overpass

rust/osm2lanes/src/road/marking.rs, rust/osm2lanes/src/transform/error.rs, rust/osm2lanes/src/transform/tags_to_lanes/mod.rs, rust/osm2lanes/src/transform/tags_to_lanes/separator.rs, rust/rust-toolchain.toml
This became a bit big, sorry...
=> Rust Refactor Separators

.github/workflows/test.yml, rust/osm2lanes/Cargo.toml
=> Rust: Enable Benchmark in PR

.github/workflows/test.yml
If we can configure the settings correctly, a bot should comment here with a nice looking table.
=> Rust: Enable Benchmarking

data/test_spec.py, data/tests.yml, kotlin/src/test/kotlin/Test.kt, python/tests/test_lanes.py, rust/osm2lanes/src/road/lane.rs, rust/osm2lanes/src/road/mod.rs, rust/osm2lanes/src/tag/osm.rs, rust/osm2lanes/src/test.rs
To give us a chance to slowly iterate on refactoring the tests :)
=> Refactor Serde Spec and Tests

data/tests.yml, rust/osm2lanes/src/road/lane.rs, rust/osm2lanes/src/test.rs, rust/osm2lanes/src/transform/tags_to_lanes/mod.rs, rust/osm2lanes/src/transform/tags_to_lanes/separator.rs
YAML Reformat
Fix Highway Inner Edge
=> Rust: Increment Tests and Separator

data/tests.yml, rust/osm2lanes/src/test.rs, rust/osm2lanes/src/transform/lanes_to_tags/mod.rs, rust/osm2lanes/src/transform/tags_to_lanes/mod.rs, rust/osm2lanes/src/transform/tags_to_lanes/non_motorized.rs
Small increment to support way 40297361
=> Rust: Add Support for Path and Steps

rust/.rustfmt.toml, rust/osm2lanes-bin/src/main.rs, rust/osm2lanes-web/src/draw.rs, rust/osm2lanes-web/src/main.rs, rust/osm2lanes/src/lib.rs, rust/osm2lanes/src/locale.rs, rust/osm2lanes/src/road/lane.rs, rust/osm2lanes/src/tag/mod.rs, rust/osm2lanes/src/tag/osm.rs, rust/osm2lanes/src/test.rs, rust/osm2lanes/src/transform/error.rs, rust/osm2lanes/src/transform/lanes_to_tags/mod.rs, rust/osm2lanes/src/transform/tags_to_lanes/bus.rs, rust/osm2lanes/src/transform/tags_to_lanes/foot_shoulder.rs, rust/osm2lanes/src/transform/tags_to_lanes/mod.rs, rust/osm2lanes/src/transform/tags_to_lanes/non_motorized.rs, rust/osm2lanes/src/transform/tags_to_lanes/separator.rs
This clippy lint group has some nice to haves like dbg!() warnings.
=> Rust: Enable Clippy Restriction

rust/osm2lanes/src/transform/lanes_to_tags/mod.rs
There are no functional changes, only a refactor into a mod + functions.
=> Rust: Refactor lanes_to_tags

.github/workflows/test.yml
Unknown ref HEAD~ because missing checkout.
=> Fix Rust Benchmark in main

rust/osm2lanes-bin/src/main.rs, rust/osm2lanes-web/Cargo.toml, rust/osm2lanes-web/assets/css/main.css, rust/osm2lanes-web/index.html, rust/osm2lanes-web/src/main.rs, rust/osm2lanes-web/src/map.rs, rust/osm2lanes/Cargo.toml, rust/osm2lanes/src/overpass.rs
Working example,
cleanups will be needed as a follow-up.
@dabreegster, I used your map as inspiration, but really struggled to get the mapbox library integrated, whereas leaflet has a rust lib already :D
=> Add Leaflet-based Slippy Map To Website

rust/osm2lanes-web/src/canvas.rs, rust/osm2lanes-web/src/control.rs, rust/osm2lanes-web/src/draw.rs, rust/osm2lanes-web/src/main.rs, rust/osm2lanes-web/src/map.rs, rust/osm2lanes/src/locale.rs
No functional changes, preparation work for other work in improving web view.
=> Rust: Refactor Web into Components

rust/osm2lanes-bin/src/main.rs, rust/osm2lanes-web/assets/css/main.css, rust/osm2lanes-web/src/main.rs, rust/osm2lanes-web/src/map.rs, rust/osm2lanes/src/locale.rs, rust/osm2lanes/src/overpass.rs
Remove double overpass query, and more cleanups
=> Rust Web: Some Minor Fixes

rust/osm2lanes/src/metric.rs, rust/osm2lanes/src/transform/tags_to_lanes/mod.rs, rust/osm2lanes/src/transform/tags_to_lanes/separator/mod.rs, rust/osm2lanes/src/transform/tags_to_lanes/separator/semantic.rs
=> Rust: Add Semantic Separator Example

rust/osm2lanes-web/src/control.rs, rust/osm2lanes-web/src/main.rs, rust/osm2lanes-web/src/map.rs, rust/osm2lanes/src/lib.rs
The way ID is now shown when selected on slippy map.
=> Rust: Rework Website

data/tests.yml, rust/osm2lanes/src/metric.rs, rust/osm2lanes/src/road/lane.rs, rust/osm2lanes/src/test.rs, rust/osm2lanes/src/transform/tags_to_lanes/mod.rs, rust/osm2lanes/src/transform/tags_to_lanes/modes/foot_shoulder.rs, rust/osm2lanes/src/transform/tags_to_lanes/separator/mod.rs, rust/osm2lanes/src/transform/tags_to_lanes/separator/semantic.rs
Referencing: https://puc.overheid.nl/rijkswaterstaat/doc/PUC_125514_31/ section 4.2.5
=> Rust: Update NL Autoweg Width

rust/osm2lanes/src/road/lane.rs, rust/osm2lanes/src/road/mod.rs, rust/osm2lanes/src/tag/access.rs, rust/osm2lanes/src/tag/mod.rs, rust/osm2lanes/src/test.rs, rust/osm2lanes/src/transform/mod.rs, rust/osm2lanes/src/transform/tags_to_lanes/modes/non_motorized.rs, rust/osm2lanes/src/transform/tags_to_lanes/road.rs
A proposal on how to add access definitions to the spec.
=> Rust: Access to Spec

rust/osm2lanes/src/transform/mod.rs, rust/osm2lanes/src/transform/tags_to_lanes/mod.rs, rust/osm2lanes/src/transform/tags_to_lanes/road.rs
A helper function for building up confidence.
=> Rust: Infer Set

.github/workflows/web.yml
=> Fix Website

osm2lanes/src/transform/tags_to_lanes/counts.rs
Move the `lane=* and lane:DIRECTION=*` to a standalone struct
=> Refactor Lane Counts

data/tests.yml
If this test is enabled, we panic
=> Add a test for #152

data/tests.yml
If enabled, we repro the panic
=> Add a test for #153

osm2lanes/src/transform/tags_to_lanes/modes/bicycle.rs
Includes examples of contradiction that should error.
=> Add Bicycle Tests Locally

osm2lanes/src/test.rs
Improve panic message on test failure.
=> Replace Generic Assertion with Panic

data/tests.yml
Combining bus:lanes and lanes:bus
=> Add Test For 679636490

osm2lanes/src/transform/tags_to_lanes/access_by_lane.rs, osm2lanes/src/transform/tags_to_lanes/mod.rs, osm2lanes/src/transform/tags_to_lanes/modes/bus/mod.rs
Another small step for this repo, and a miniscule step for mankind.
=> Refactor Access By Lane for lanes:bus

data/tests.yml, osm2lanes-web/src/draw.rs, osm2lanes/benches/benchmark_tests.rs, osm2lanes/benches/benchmark_tests_sample.rs, osm2lanes/src/test.rs, osm2lanes/src/transform/lanes_to_tags/mod.rs, osm2lanes/src/transform/tags_to_lanes/infer.rs, osm2lanes/src/transform/tags_to_lanes/modes/bicycle.rs, osm2lanes/src/transform/tags_to_lanes/modes/foot_shoulder.rs, osm2lanes/src/transform/tags_to_lanes/road.rs, osm2lanes/src/transform/tags_to_lanes/separator/mod.rs, osm2lanes/src/transform/tags_to_lanes/separator/semantic.rs
=> Add Lambeth Bridge Test

data/tests.yml, osm2lanes/src/metric.rs, osm2lanes/src/transform/tags_to_lanes/road.rs
=> Handle Maxspeed Bugs Gracefully

data/tests.yml, osm2lanes/src/transform/tags_to_lanes/modes/bicycle.rs
As discussed in https://github.com/a-b-street/osm2lanes/issues/162
=> Refactor Bicycle for opposite_*

osm2lanes/src/transform/tags_to_lanes/error.rs, osm2lanes/src/transform/tags_to_lanes/modes/bicycle.rs
Commits may be reviewed separately if preferred.
=> Refactor bicycle

osm-tags/src/lib.rs, osm2lanes-npm/src/lib.rs, osm2lanes/src/tag.rs, osm2lanes/src/transform/lanes_to_tags/mod.rs
A common newbie rust mistake: overuse traits
=> Remove TagsWrite

osm2lanes/src/overpass.rs
Fail more gracefully when retrieving data from overpass fails.
One example: clicking somewhere more than 100m from any way will crash the website.
=> Overpass Error

osm2lanes-web/Cargo.toml, osm2lanes-web/assets/css/main.css, osm2lanes-web/index.html, osm2lanes-web/src/main.rs, osm2lanes-web/src/map.rs
Why: I am starting to implement `Access`, but I want to see the values in the web interface somehow.
Problem: This murders performance. if loading examples, was slow, this is really painful... about 3 times slower or something for the syntax highlighting. The goal should definitely be to make it lazy...
=> Json + Hghlighting on website

osm2lanes/src/tag.rs, osm2lanes/src/transform/tags_to_lanes/mod.rs, osm2lanes/src/transform/tags_to_lanes/modes/bus/busway.rs, osm2lanes/src/transform/tags_to_lanes/modes/bus/mod.rs, osm2lanes/src/transform/tags_to_lanes/modes/mod.rs, osm2lanes/src/transform/tags_to_lanes/road.rs
Yank Schemes to the top level to parse them out first.
=> Refactor Road, Counts, and Busway

osm2lanes/src/lib.rs, osm2lanes/src/metric.rs, osm2lanes/src/test.rs, osm2lanes/src/transform/lanes_to_tags/mod.rs, osm2lanes/src/transform/mod.rs, osm2lanes/src/transform/tags_to_lanes/access_by_lane.rs, osm2lanes/src/transform/tags_to_lanes/counts.rs, osm2lanes/src/transform/tags_to_lanes/error.rs, osm2lanes/src/transform/tags_to_lanes/mod.rs, osm2lanes/src/transform/tags_to_lanes/modes/bus/busway.rs, osm2lanes/src/transform/tags_to_lanes/modes/bus/mod.rs, osm2lanes/src/transform/tags_to_lanes/road.rs, osm2lanes/src/transform/tags_to_lanes/unsupported.rs
Normalize osm2lanes to osm-tags for clippy.
=> Clippy Fixes

data/tests.yml, osm2lanes-web/src/draw.rs, osm2lanes/src/metric.rs, osm2lanes/src/road/lane.rs, osm2lanes/src/test.rs, osm2lanes/src/transform/lanes_to_tags/mod.rs, osm2lanes/src/transform/tags_to_lanes/modes/bicycle.rs, osm2lanes/src/transform/tags_to_lanes/modes/mod.rs, osm2lanes/src/transform/tags_to_lanes/road.rs, osm2lanes/src/transform/tags_to_lanes/separator/mod.rs, osm2lanes/src/transform/tags_to_lanes/separator/semantic.rs
Required a schema change for markings,
update to the test infrastructure,
a new drawing option
=> Support Cycleway Opposite Track

osm2lanes/src/transform/tags_to_lanes/mod.rs, osm2lanes/src/transform/tags_to_lanes/modes/bicycle.rs
=> Support Cycleway Conflicting Tags

.githooks/check, .githooks/test_rust, .github/workflows/test.yml, osm-tag-schemes/Cargo.toml, osm-tag-schemes/src/access.rs, osm-tag-schemes/src/highway.rs, osm-tag-schemes/src/lib.rs, osm-tag-schemes/src/smoothness.rs, osm-tag-schemes/src/track_type.rs, osm-tags/Cargo.toml, osm-tags/src/lib.rs, osm2lanes/Cargo.toml, osm2lanes/src/locale.rs, osm2lanes/src/metric.rs, osm2lanes/src/overpass.rs, osm2lanes/src/road/lane.rs, osm2lanes/src/road/mod.rs, osm2lanes/src/road/separator.rs, osm2lanes/src/test.rs, osm2lanes/src/transform/error.rs, osm2lanes/src/transform/tags_to_lanes/error.rs
gives clients control of compilation cost/size
=> Add cfg for serde

.github/workflows/crate-deploy.yml
=> Deploy Crate osm-tags

osm2lanes-web/src/map.rs, osm2lanes/src/overpass.rs
=> Add Circle When Searching

pyproject.toml, requirements.txt
Reverts a-b-street/osm2lanes#250
Ah, we have some tests of the JSON schema using Python. Oops!
=> Revert "Remove old python config, missed in #147"
